name: Pre-process and prepare build

on:
  push:
    branches:
      - ghpages-fix

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "prepare-pages"
  cancel-in-progress: true

jobs:

  pre-process:
    name: Pre-process site for build
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout git
        uses: actions/checkout@v3
        with:
          path: src

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/scripts/requirements.txt"

      - name: Prepare build - generate pages
        working-directory: src/scripts/deploy
        run: python3 ./prepare_build.py --max_bodies_per_jurisdiction 1000

      - name: Prepare stage branch
        working-directory: src
        run: |
          mkdir -p website/.github/workflows/
          cp .github/workflows/publish_site.yaml website/.github/workflows/
          rm -rf .git
          cd website
          git init .

      # - name: Commit to stage
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.ref == 'refs/heads/ghpages-fix' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages-stage
      #     publish_dir: src/website

      - name: Update branch to include action
        uses: actions-x/commit@v6
        with:
          branch: gh-pages-stage
          directory: src/website
          email: 41898282+github-actions[bot]@users.noreply.github.com
          name: GitHub Actions Update Bot
          message: Update branch to include action

      # - name: Update branch to include action
      #   uses: benkaiser/rebase-commit-push@v1.1
      #   with:
      #     branch: gh-pages-stage
      #     directory: gh-pages-stage
      #     author_email: 41898282+github-actions[bot]@users.noreply.github.com
      #     author_name: GitHub Actions Update Bot
      #     message: Update branch to include action
      #     rebase: true
