name: Pre-process and prepare build

on:
  push:
    branches:
      - ghpages-fix

jobs:

  pre-process:
    runs-on: ubuntu-22.04
    name: Pre-process site for build
    steps:

      - name: Checkout git
        uses: actions/checkout@v3
        with:
          path: src

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/scripts/requirements.txt"

      - name: Prepare build
        working-directory: src/scripts/deploy
        run: python3 ./prepare_build.py --max_bodies_per_jurisdiction 1000

      - name: Copy deploy action to branch
        run: |
          mkdir -p website/.github/workflows/
          cp .github/workflows/publish_site.yaml website/.github/workflows/

      - name: Commit to stage
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/ghpages-fix' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-stage
          publish_dir: src/website
