name: Publish site

on:
  push:
    branches: [ "gh-pages-stage" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  JEKYLL_VERSION: 4.2.0

jobs:

  build:

    name: Build with Jekyll
    runs-on: ubuntu-latest
    # container: jekyll/minimal:4.2.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages-stage

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2    # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
