name: Publish site

on:
  push:
    branches: [ "ghpages-fix" ]

env:
  JEKYLL_VERSION: 4.2.0

jobs:
  build:
    name: Build with Jekyll and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Build Jekyll Site
        run: docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/minimal:$JEKYLL_VERSION jekyll build --baseurl $PWD/_site/ --incremental
          working-directory: website/

      - name: commit & push with rebase
        uses: benkaiser/rebase-commit-push@v1.1
        with:
          branch: ghpages-fix
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          author_name: GitHub Actions Update Bot
          message: Site updated automatically by bot
          rebase: true
