name: Publish site

on:
  push:
    branches: [ "ghpages-fix" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  JEKYLL_VERSION: 4.2.0

jobs:

  build:

    name: Build with Jekyll
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      # - name: commit & push with rebase
      #   uses: benkaiser/rebase-commit-push@v1.1
      #   with:
      #     branch: ghpages-fix
      #     author_email: 41898282+github-actions[bot]@users.noreply.github.com
      #     author_name: GitHub Actions Update Bot
      #     message: Site updated automatically by bot
      #     rebase: true

      - name: Setup Pages
        uses: actions/configure-pages@v2

      # - name: Build with Jekyll
      #   uses: actions/jekyll-build-pages@v1
      #   with:
      #     source: ./
      #     destination: ./_site

      - name: Build Jekyll Site
        run: docker run --rm --volume="$PWD:/srv/jekyll" jekyll/minimal:$JEKYLL_VERSION jekyll build --baseurl /

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:

    name: Deploy to Github Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
